#!/usr/bin/env bash
# This script extends previous exercise command and displays line containing the bash word, this aloowing you to easily get the PID of your Bash process
# You cannot use pgrep
# shellcheck disable=SC2009

./1-list_your_processes | grep "bash"
